
thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
